// AUTO-GENERATED by tools/gen_mn_phonemes.py (EMPTY: g2p_en unavailable). Do not edit.
// MultiNet7 phonemes per phrase (g2p_en + esp-sr alphabet).
#pragma once
struct MnPhoneme { const char* text; const char* ph; };
static const MnPhoneme MN_PHONEMES[] = {
    {nullptr, nullptr},
};
static const int MN_PHONEMES_N = 0;
