#!/usr/bin/env python3
"""
gen_mn_phonemes.py — precompute MultiNet7 English phonemes for every phrase in
the fox's COMMANDS table, the way Espressif recommends.

Why: esp_mn_commands_add() runs a generic runtime G2P (flite_g2p) and Espressif
documents "a little accuracy drop" from it. Their recommended path is
tool/multinet_g2p.py (g2p_en + a fixed ARPAbet->MultiNet alphabet), registered
with esp_mn_commands_phoneme_add(). This script reproduces that tool exactly
(same alphabet table) and writes firmware/main/mn_phonemes.h.

Check: "tell me a joke" -> "TfL Mm c qbK", identical to Espressif's docs.

If g2p_en is unavailable (no network), it writes an EMPTY table: the firmware
then falls back to runtime G2P, so the build never breaks.
"""
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "firmware", "main", "fox_main.cpp")
OUT = os.path.join(ROOT, "firmware", "main", "mn_phonemes.h")

# Verbatim from espressif/esp-sr tool/multinet_g2p.py
ALPHABET = {"AE1": "a", "N": "N", " ": " ", "OW1": "b", "V": "V", "AH0": "c", "L": "L", "F": "F", "EY1": "d", "S": "S", "B": "B", "R": "R", "AO1": "e", "D": "D", "AH1": "c", "EH1": "f", "OW0": "b", "IH0": "g", "G": "G", "HH": "h", "K": "K", "IH1": "g", "W": "W", "AY1": "i", "T": "T", "M": "M", "Z": "Z", "DH": "j", "ER0": "k", "P": "P", "NG": "l", "IY1": "m", "AA1": "n", "Y": "Y", "UW1": "o", "IY0": "m", "EH2": "f", "CH": "p", "AE0": "a", "JH": "q", "ZH": "r", "AA2": "n", "SH": "s", "AW1": "t", "OY1": "u", "AW2": "t", "IH2": "g", "AE2": "a", "EY2": "d", "ER1": "k", "TH": "v", "UH1": "w", "UW2": "o", "OW2": "b", "AY2": "i", "UW0": "o", "AH2": "c", "EH0": "f", "AW0": "t", "AO2": "e", "AO0": "e", "UH0": "w", "UH2": "w", "AA0": "n", "AY0": "i", "IY2": "m", "EY0": "d", "ER2": "k", "OY2": "u", "OY0": "u"}


def phrases():
    t = open(SRC).read()
    block = t[t.index("static const Command COMMANDS[]"):t.index("static const size_t COMMAND_COUNT")]
    out = []
    for _id, ph, _a in re.findall(r'\{(\d+),\s+"([^"]+)",\s+"([^"]+)"\}', block):
        for p in ph.split(";"):
            p = re.sub(r"[^a-z ]", "", p.lower()).strip()
            if p and p not in out:
                out.append(p)
    return out


def write(entries, note):
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_mn_phonemes.py (%s). Do not edit.\n" % note)
        f.write("// MultiNet7 phonemes per phrase (g2p_en + esp-sr alphabet).\n")
        f.write("#pragma once\nstruct MnPhoneme { const char* text; const char* ph; };\n")
        f.write("static const MnPhoneme MN_PHONEMES[] = {\n")
        for text, ph in entries:
            f.write('    {"%s", "%s"},\n' % (text, ph))
        if not entries:
            f.write("    {nullptr, nullptr},\n")
        f.write("};\nstatic const int MN_PHONEMES_N = %d;\n" % len(entries))


def main():
    try:
        import nltk
        for res in ("averaged_perceptron_tagger", "averaged_perceptron_tagger_eng", "cmudict"):
            try: nltk.download(res, quiet=True)
            except Exception: pass
        from g2p_en import G2p
    except Exception as e:
        print("gen_mn_phonemes: g2p_en unavailable (%s) -> empty table, runtime G2P fallback" % e)
        write([], "EMPTY: g2p_en unavailable")
        return 0
    g2p = G2p()
    entries, skipped = [], 0
    for p in phrases():
        labels = g2p(p)
        out = "".join(ALPHABET[c] for c in labels if c in ALPHABET)
        out = re.sub(" +", " ", out).strip()
        if out:
            entries.append((p, out))
        else:
            skipped += 1
    check = dict(entries).get("tell me a joke")
    print("gen_mn_phonemes: %d phrases, skipped %d; 'tell me a joke' -> %r (docs: 'TfL Mm c qbK')"
          % (len(entries), skipped, check))
    write(entries, "g2p_en")
    return 0


if __name__ == "__main__":
    sys.exit(main())
